development:
  adapter: postgresql
  database: tricho_dev
  username: postgres
  host: localhost

test:
  adapter: postgresql
  database: tricho_test
  username: postgres
  host: localhost

production:
  adapter: postgresql
  database: tricho_prod
  username: guspares
  password: sean1
